#: set color1 (255/255, 153/255, 51/255, 1)
#: set color2 (80/255, 52/255, 24/255, 1)
#: set color3 (238/255, 238/255, 238/255, 1)
#: set color4 (1, 1, 1, 1)
#: set color5 (0, 0, 0, 1)
#: set color6 (1, 0, 0, 1)

#: set scroll_padding 55

#: set bold_font "Roboto-Bold.ttf"
#: set regular_font "Roboto-Regular.ttf"
#: set monoRegular_font "RobotoMono-Regular.ttf"

#: set img_dir "./data/images/"
#: set tms_file_icon "logo1.ico"

